#ifndef RENDER_ICON_CODEPOINTS_H
#define RENDER_ICON_CODEPOINTS_H

#define R_ICON_STAR              0xE800
#define R_ICON_STAR_EMPTY        0xE801
#define R_ICON_CHECK             0xE802
#define R_ICON_CROSS             0xE80F
#define R_ICON_PLUS              0xE810
#define R_ICON_QUESTIONMARK      0xF128
#define R_ICON_INFO              0xF129
#define R_ICON_LINK              0xE804
#define R_ICON_LOCK              0xE805
#define R_ICON_LOCK_OPEN         0xE806
#define R_ICON_LOCK_OPEN_ALT     0xF13E
#define R_ICON_LINK_EXT          0xF08E
#define R_ICON_PIN               0xE807
#define R_ICON_BOOKMARK          0xE808
#define R_ICON_BOOOKMARK_EMPTY   0xF097
#define R_ICON_REPLY             0xF112
#define R_ICON_FORWARD           0xE809
#define R_ICON_ATTENTION         0xF12A
#define R_ICON_TRASH             0xF1F8
#define R_ICON_FOLDER            0xE80A
#define R_ICON_FOLDER_OPEN       0xE80B
#define R_ICON_MENU              0xF0C9
#define R_ICON_COG               0xE80C
#define R_ICON_RESIZE_FULL       0xE80D
#define R_ICON_RESIZE_FULL_ALT   0xF0B2
#define R_ICON_RESIZE_SMALL      0xE80E
#define R_ICON_RESIZZE_VERTICAL  0xE811
#define R_ICON_RESIZE_HORIZONTAL 0xE812
#define R_ICON_MOVE              0xF047
#define R_ICON_ZOOM_IN           0xE813
#define R_ICON_ZOOM_OUT          0xE814
#define R_ICON_DOWN_OPEN         0xE815
#define R_ICON_LEFT_OPEN         0xE816
#define R_ICON_RIGHT_OPEN        0xE817
#define R_ICON_UP_OPEN           0xE818
#define R_ICON_DOWN              0xF175
#define R_ICON_LEFT              0xF177
#define R_ICON_RIGHT             0xF178
#define R_ICON_UP                0xF176
#define R_ICON_DOWN_BIG          0xE819
#define R_ICON_LEFT_BIG          0xE81A
#define R_ICON_RIGHT_BIG         0xE81B
#define R_ICON_UP_BIG            0xE81C
#define R_ICON_REFRESH           0xE81D
#define R_ICON_PLAY              0xE803
#define R_ICON_STOP              0xE81E
#define R_ICON_PAUSE             0xE81F
#define R_ICON_TO_END            0xE820
#define R_ICON_TO_END_ALT        0xE812
#define R_ICON_TO_START          0xE822
#define R_ICON_TO_START_ALT      0xE823
#define R_ICON_FAST_FORWARD      0xE824
#define R_ICON_FAST_BACKWARD     0xE825
#define R_ICON_LIST              0xE826
#define R_ICON_LIST_BULLET       0xF0CA
#define R_ICON_ADJUST            0xE827

#endif //RENDER_ICON_CODEPOINTS_H
