workspace = { members = ["framed_macro"] }

[package]
name = "framed-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "framed"
path = "src/lib.rs"

[build-dependencies]
cc = "1.0.88"

[dependencies]
framed-rs-macros = { path = "./framed_macro" }

[[bin]]
name = "simple_init_and_send"
path = "src/examples/simple_init_and_send.rs"

[[bin]]
name = "zones"
path = "src/examples/zones.rs"
